"""
approvals_page.py — Execution Control Room to trigger downstream autonomous workflows safely.
"""
from __future__ import annotations

import streamlit as st
import json

from utils.helpers import sort_findings
from utils.constants import SEVERITY_COLORS
from core.cost_calculator import format_inr
from core.action_engine import execute_action
from workflows.approval_manager import (
    init_approvals, get_approval_status,
    set_approval_status, pending_count, approved_savings,
)

def render(findings: list) -> None:
    st.markdown("""
    <style>
    .exec-card {
        background: rgba(8,8,22,0.9); border: 1px solid rgba(139,92,246,0.25);
        border-radius: 16px; padding: 24px; margin-bottom: 24px;
        box-shadow: 0 8px 32px rgba(0,0,0,0.4);
    }
    .exec-head { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid rgba(255,255,255,0.08); padding-bottom: 16px; margin-bottom: 16px; }
    .exec-title { font-weight: 800; color: #f1f5f9; font-size: 1.1rem; }
    .exec-impact { color: #a78bfa; font-weight: 900; font-size: 1.25rem; }
    .payload-box {
        background: #020205; border: 1px solid #1e1b4b; border-radius: 12px;
        padding: 16px; font-family: 'Courier New', monospace; font-size: 0.8rem;
        color: #34d399; overflow-x: auto;
    }
    .payload-title { font-size: 0.7rem; color: #64748b; text-transform: uppercase; font-weight: 700; letter-spacing: 0.05em; margin-bottom: 8px; }
    </style>
    """, unsafe_allow_html=True)

    st.markdown("## 🔐 Execution Control Room")
    st.markdown("<p style='color:#94a3b8;margin-bottom:32px'>Review and authorize actionable API payloads generated by ACIA agents before releasing to enterprise production parameters.</p>", unsafe_allow_html=True)

    if not findings:
        st.info("No agents are requesting execution authority. 📂 Upload Data to initiate.")
        return

    init_approvals(findings)
    sorted_findings = sort_findings(findings, "annual_impact")
    
    pend = pending_count(findings)
    if pend == 0:
        st.success("🎉 Execution Queue is completely clear. No outstanding agent tasks.")

    for i, f in enumerate(sorted_findings):
        status = get_approval_status(i, f)
        
        # Only show pending items strictly in this view
        if status != "pending":
            continue
            
        sev = f.get("severity", "LOW")
        color = SEVERITY_COLORS.get(sev, "#6b7280")
        
        # Generate the simulation payload to show to the user BEFORE they execute
        # We temporarily invoke it conceptually to display the JSON (in reality, action_engine.py generates this instantly)
        from core.action_engine import execute_action
        
        st.markdown(f"""
        <div class="exec-card">
            <div class="exec-head">
                <div class="exec-title">{f.get('severity_emoji','')} {f.get('title','')}</div>
                <div class="exec-impact" style="color:{color}">Recover {f.get('formatted_impact','')}/yr</div>
            </div>
            <p style="color:#94a3b8; font-size:0.9rem; margin-bottom:16px;">{f.get('description','')}</p>
        </div>
        """, unsafe_allow_html=True)
        
        c1, c2 = st.columns([1.5, 1])
        with c1:
            st.markdown("<div class='payload-title'>⚙️ Pending Outbound Execution Payload (API Request)</div>", unsafe_allow_html=True)
            # Just do a dry-run execution to extract the payload to show the user
            dry_run_payload = execute_action(f, approved_by="DryRun Preview", dry_run=True)
            payload_str = dry_run_payload.get('payload', '{}')
            st.markdown(f"<div class='payload-box'>{payload_str}</div>", unsafe_allow_html=True)
        
        with c2:
            st.markdown("<div class='payload-title'>🔐 Authorization Required</div>", unsafe_allow_html=True)
            st.markdown(f"<div style='background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:16px;font-size:0.85rem;color:#94a3b8'>By approving, you authorize the agent to execute this API payload against connected enterprise endpoints to realize financial reclamation.</div>", unsafe_allow_html=True)
            st.markdown("<br>", unsafe_allow_html=True)
            
            # Action Buttons
            bc1, bc2 = st.columns(2)
            with bc1:
                if st.button("🚀 AUTHORIZE EXECUTION", key=f"auth_{i}", type="primary", use_container_width=True):
                    set_approval_status(i, f, "approved")
                    st.success("✅ Payload executed successfully. Webhook deployed.")
                    st.rerun()
            with bc2:
                if st.button("❌ Deny Payload", key=f"deny_{i}", use_container_width=True):
                    set_approval_status(i, f, "rejected")
                    st.rerun()
        
        st.markdown("---")
